# Generated by Django 4.2.2 on 2023-06-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('authors', models.CharField(max_length=30)),
                ('descrição', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=30)),
            ],
        ),
    ]
