# Generated by Django 4.2.2 on 2023-06-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_rename_descrição_livro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='esta_disponivel',
            field=models.BooleanField(default=False),
        ),
    ]
