# Generated by Django 4.2.2 on 2023-06-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_livro_esta_disponivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='authors',
            new_name='autor',
        ),
    ]
