# Generated by Django 4.2.1 on 2023-06-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_rename_authors_livro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='esta_disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
