# Generated by Django 4.2.2 on 2023-06-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0003_remove_emprestimo_situacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_conclusao_emprestimo',
            field=models.DateField(null=True),
        ),
    ]
