# Generated by Django 4.2.1 on 2023-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pode_fazer_emprestimo',
            field=models.BooleanField(default=False),
        ),
    ]
