# Generated by Django 4.2.1 on 2023-06-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_pode_fazer_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=999999, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
