# Generated by Django 4.2.2 on 2023-06-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pode_fazer_emprestimo',
            field=models.BooleanField(default=True),
        ),
    ]
